import type { MatchResult, Occupation, VacanciesResponse } from "@azuki/shared";

export const MOCK_MATCH_RESULT: MatchResult = {
	occupations: [
		{
			id: 10001,
			name: "Fachinformatiker/in Anwendungsentwicklung",
			rawName: "Fachinformatikerin Anwendungsentwicklung",
			score: 0.94,
			images: [],
			shortDescription:
				"Du entwickelst Software und Apps – von der Idee über Planung und Programmierung bis zum fertigen Produkt.",
			reasoning:
				"Deine Stärken in logischem Denken und dein Interesse an Technik passen perfekt zu diesem Beruf.",
			occupationType: "dual",
			occupationTag: "computer-it",
			occupationDuration: "3 Jahre",
			occupationEarnings: "620-800 € / Monat",
			salaryKnown: true,
			salaryMonthlyMedian: 3200,
		},
		{
			id: 10002,
			name: "Kaufmann/-frau für Büromanagement",
			rawName: "Kauffrau für Büromanagement",
			score: 0.87,
			images: [],
			shortDescription:
				"Du organisierst Büroabläufe, koordinierst Termine und bist die Schaltstelle zwischen Abteilungen und Kunden.",
			reasoning:
				"Dein Organisationstalent und deine Kommunikationsstärke machen dich zur perfekten Besetzung für diesen Beruf.",
			occupationType: "dual",
			occupationTag: "buero-verwaltung-logistik",
			occupationDuration: "3 Jahre",
			occupationEarnings: "550-700 € / Monat",
			salaryKnown: true,
			salaryMonthlyMedian: 2600,
		},
		{
			id: 10003,
			name: "Elektroniker/in Energie- und Gebäudetechnik",
			rawName: "Elektroniker Energie- und Gebäudetechnik",
			score: 0.82,
			images: [],
			shortDescription:
				"Du installierst und wartest elektrische Anlagen in Gebäuden – von der Steckdose bis zur Heizungssteuerung.",
			reasoning:
				"Handwerkliches Geschick und technisches Interesse zeichnen dich aus – ideal für diesen Ausbildungsberuf.",
			occupationType: "dual",
			occupationTag: "elektro-energie",
			occupationDuration: "3,5 Jahre",
			occupationEarnings: "700-850 € / Monat",
			salaryKnown: true,
			salaryMonthlyMedian: 3100,
		},
		{
			id: 10004,
			name: "Medizinische/r Fachangestellte/r",
			rawName: "Medizinische Fachangestellte",
			score: 0.78,
			images: [],
			shortDescription:
				"Du unterstützt Ärzte bei der Patientenversorgung, nimmst Blut ab, verwaltest Patientendaten und koordinierst Praxisabläufe.",
			reasoning:
				"Deine Empathie und dein Interesse an Gesundheitsthemen passen gut zu diesem Beruf.",
			occupationType: "dual",
			occupationTag: "gesundheit",
			occupationDuration: "3 Jahre",
			occupationEarnings: "600-750 € / Monat",
			salaryKnown: true,
			salaryMonthlyMedian: 2800,
		},
		{
			id: 10005,
			name: "Koch/Köchin",
			rawName: "Koch",
			score: 0.73,
			images: [],
			shortDescription:
				"Du bereitest täglich frische Gerichte zu, planst Menüs und arbeitest in einem Team – ob im Restaurant, Hotel oder in der Gemeinschaftsverpflegung.",
			reasoning:
				"Kreativität in der Küche und Freude an Teamarbeit sind deine Stärken.",
			occupationType: "dual",
			occupationTag: "essen-gastronomie",
			occupationDuration: "3 Jahre",
			occupationEarnings: "650-800 € / Monat",
			salaryKnown: true,
			salaryMonthlyMedian: 2400,
		},
		{
			id: 10006,
			name: "Kaufmann/-frau im Einzelhandel",
			rawName: "Kauffrau im Einzelhandel",
			score: 0.69,
			images: [],
			shortDescription:
				"Du berätst Kunden, pflegst das Warensortiment und sorgst dafür, dass der Laden reibungslos läuft.",
			reasoning:
				"Deine Kundenorientierung und Kommunikationsfreude kommen im Einzelhandel täglich zum Einsatz.",
			occupationType: "dual",
			occupationTag: "verkaufen-beraten",
			occupationDuration: "3 Jahre",
			occupationEarnings: "550-700 € / Monat",
			salaryKnown: true,
			salaryMonthlyMedian: 2300,
		},
		{
			id: 10007,
			name: "Tischler/in",
			rawName: "Tischler",
			score: 0.65,
			images: [],
			shortDescription:
				"Du entwirfst und fertigst Möbel, Fenster und Treppen aus Holz – handwerklich präzise und mit Sinn für Gestaltung.",
			reasoning:
				"Dein handwerkliches Geschick und dein Sinn für Ästhetik passen gut zur Tischlerei.",
			occupationType: "dual",
			occupationTag: "bauen-handwerk",
			occupationDuration: "3 Jahre",
			occupationEarnings: "600-750 € / Monat",
			salaryKnown: true,
			salaryMonthlyMedian: 2700,
		},
		{
			id: 10008,
			name: "Erzieher/in",
			rawName: "Erzieherin",
			score: 0.61,
			images: [],
			shortDescription:
				"Du begleitest Kinder in ihrer Entwicklung, planst pädagogische Angebote und arbeitest eng mit Familien zusammen.",
			reasoning:
				"Deine Empathie und Freude am Arbeiten mit Menschen machen dich zu einem wertvollen Teil jedes pädagogischen Teams.",
			occupationType: "school",
			occupationTag: "soziales-betreuen",
			occupationDuration: "3 Jahre",
			occupationEarnings: "",
			salaryKnown: false,
			salaryMonthlyMedian: null,
		},
	],
};

export const MOCK_VACANCIES_RESPONSE: VacanciesResponse = {
	results: [
		{
			occupation: "Fachinformatikerin Anwendungsentwicklung",
			totalCount: 42,
			previews: [
				{
					employer: "Muster GmbH",
					city: "Berlin",
					postcode: "10115",
					district: "Mitte",
					startDate: "2025-09-01",
					publishedAt: "2025-03-15",
				},
				{
					employer: "Tech Solutions AG",
					city: "Berlin",
					postcode: "10587",
					district: "Charlottenburg",
					startDate: "2025-08-01",
					publishedAt: "2025-03-10",
				},
			],
			searchUrl:
				"https://www.arbeitsagentur.de/jobsuche/suche?was=Fachinformatiker+Anwendungsentwicklung&wo=Berlin",
		},
		{
			occupation: "Kauffrau für Büromanagement",
			totalCount: 28,
			previews: [
				{
					employer: "Verwaltungs GmbH",
					city: "Berlin",
					postcode: "12043",
					district: "Neukölln",
					startDate: "2025-09-01",
					publishedAt: "2025-03-08",
				},
			],
			searchUrl:
				"https://www.arbeitsagentur.de/jobsuche/suche?was=Kaufmann+Bueromanagement&wo=Berlin",
		},
		{
			occupation: "Elektroniker Energie- und Gebäudetechnik",
			totalCount: 19,
			previews: [
				{
					employer: "Energie Plus GmbH",
					city: "Berlin",
					postcode: "13347",
					district: "Wedding",
					startDate: "2025-09-01",
					publishedAt: "2025-02-28",
				},
			],
			searchUrl:
				"https://www.arbeitsagentur.de/jobsuche/suche?was=Elektroniker+Energie&wo=Berlin",
		},
	],
};

const BASE_CONDITIONS = {
	outdoor: false,
	office: false,
	workshop: false,
	indoor: false,
	constructionSite: false,
	screenWork: false,
	manualLabor: false,
	machinery: false,
	noise: false,
	dirt: false,
	heavyLifting: false,
	heights: false,
	shiftWork: false,
	customerContact: false,
	teamwork: false,
	standingWalking: false,
	irregularHours: false,
	changingTasks: false,
	regulatedWork: false,
	animalWork: false,
	accidentRisk: false,
	precisionWork: false,
	frequentAbsence: false,
	changingWorkplaces: false,
};

const MOCK_OCCUPATIONS_LIST: Occupation[] = [
	{
		id: 10001,
		name: "Fachinformatiker/in Anwendungsentwicklung",
		descriptionShort:
			"Berufstyp Anerkannter Ausbildungsberuf Ausbildungsart Duale Ausbildung in Industrie und Handel Ausbildungsdauer 3 Jahre Lernorte Ausbildungsbetrieb und Berufsschule",
		descriptionLong: null,
		taskSummary: null,
		shortDescription:
			"Apps und Software entwickeln – von der Idee bis zum fertigen Produkt.",
		taskBullets: [
			"Code schreiben und Programme testen",
			"Fehler im Code suchen und beheben",
			"Mit dem Team neue Funktionen planen",
			"Datenbanken einrichten und pflegen",
		],
		images: [],
		degreeStats: {
			noQualification: 2,
			secondary: 15,
			intermediate: 38,
			universityEntrance: 45,
		},
		accessLevel: "realschule",
		subjects: ["Mathematik", "Informatik", "Englisch"],
		interests: ["Informatik", "Technik", "Mathematik", "Logik"],
		interestKeywords: ["programmieren", "software", "entwicklung", "IT"],
		strengthTags: ["logisches-denken", "problemloesen", "kreativitaet"],
		skillTags: ["IT", "Programmierung", "Teamarbeit"],
		conditions: {
			...BASE_CONDITIONS,
			indoor: true,
			office: true,
			screenWork: true,
			teamwork: true,
			changingTasks: true,
			precisionWork: true,
		},
		salaryMonthlyMedian: 3200,
		salaryKnown: true,
		digitalizationSignal: true,
		workLocations: "Büros, IT-Abteilungen, Homeoffice",
		competenciesText:
			"Logisches Denken, Problemlösungskompetenz, Teamfähigkeit",
		germanOccupationCode: "43304",
	},
	{
		id: 10002,
		name: "Kaufmann/-frau für Büromanagement",
		descriptionShort:
			"Berufstyp Anerkannter Ausbildungsberuf Ausbildungsart Duale Ausbildung in Industrie und Handel Ausbildungsdauer 3 Jahre Lernorte Ausbildungsbetrieb und Berufsschule",
		descriptionLong: null,
		taskSummary: null,
		shortDescription:
			"Büroabläufe organisieren, Termine koordinieren und Kunden betreuen.",
		taskBullets: [
			"Briefe schreiben und E-Mails beantworten",
			"Termine planen und Kalender pflegen",
			"Rechnungen vorbereiten und ablegen",
			"Besucher empfangen und weiterleiten",
		],
		images: [],
		degreeStats: {
			noQualification: 3,
			secondary: 20,
			intermediate: 50,
			universityEntrance: 27,
		},
		accessLevel: "hauptschule",
		subjects: ["Deutsch", "Mathematik", "Wirtschaft"],
		interests: ["Organisation", "Kommunikation", "Büro", "Verwaltung"],
		interestKeywords: ["büro", "organisation", "verwaltung", "kaufmann"],
		strengthTags: ["organisation", "kommunikation", "sorgfalt"],
		skillTags: ["Organisation", "Kommunikation", "Bürosoftware"],
		conditions: {
			...BASE_CONDITIONS,
			indoor: true,
			office: true,
			screenWork: true,
			customerContact: true,
			teamwork: true,
			regulatedWork: true,
		},
		salaryMonthlyMedian: 2600,
		salaryKnown: true,
		digitalizationSignal: true,
		workLocations: "Büros, Verwaltungsräume",
		competenciesText: "Organisationstalent, Kommunikationsstärke, Sorgfalt",
		germanOccupationCode: "71304",
	},
	{
		id: 10003,
		name: "Elektroniker/in Energie- und Gebäudetechnik",
		descriptionShort:
			"Berufstyp Anerkannter Ausbildungsberuf Ausbildungsart Duale Ausbildung in Industrie und Handwerk Ausbildungsdauer 3,5 Jahre Lernorte Ausbildungsbetrieb und Berufsschule",
		descriptionLong: null,
		taskSummary: null,
		shortDescription:
			"Elektrische Anlagen in Gebäuden installieren, warten und reparieren.",
		taskBullets: [
			"Kabel verlegen und Steckdosen einbauen",
			"Heizungs- und Lichtsteuerungen einrichten",
			"Störungen aufspüren und beheben",
			"Anlagen nach Vorschrift prüfen und dokumentieren",
		],
		images: [],
		degreeStats: {
			noQualification: 5,
			secondary: 35,
			intermediate: 45,
			universityEntrance: 15,
		},
		accessLevel: "hauptschule",
		subjects: ["Mathematik", "Physik", "Technik"],
		interests: ["Elektrotechnik", "Technik", "Handwerk"],
		interestKeywords: ["elektro", "energie", "gebäude", "installation"],
		strengthTags: ["handwerkliches-geschick", "praezision", "problemloesen"],
		skillTags: ["Elektrotechnik", "Handwerk", "Technik"],
		conditions: {
			...BASE_CONDITIONS,
			indoor: true,
			workshop: true,
			manualLabor: true,
			machinery: true,
			noise: true,
			precisionWork: true,
			teamwork: true,
			changingWorkplaces: true,
		},
		salaryMonthlyMedian: 3100,
		salaryKnown: true,
		digitalizationSignal: true,
		workLocations: "Baustellen, Gebäude, Werkstätten",
		competenciesText:
			"Handwerkliches Geschick, technisches Verständnis, Sorgfalt",
		germanOccupationCode: "26204",
	},
	{
		id: 10004,
		name: "Medizinische/r Fachangestellte/r",
		descriptionShort:
			"Berufstyp Anerkannter Ausbildungsberuf Ausbildungsart Duale Ausbildung in Industrie und Handel Ausbildungsdauer 3 Jahre Lernorte Ausbildungsbetrieb und Berufsschule",
		descriptionLong: null,
		taskSummary: null,
		shortDescription:
			"Patienten betreuen, Blut abnehmen und den Praxisalltag organisieren.",
		taskBullets: [
			"Blut abnehmen und Wunden versorgen",
			"Patientendaten erfassen und pflegen",
			"Termine vergeben und Praxisabläufe koordinieren",
			"Arzt bei Untersuchungen assistieren",
		],
		images: [],
		degreeStats: {
			noQualification: 2,
			secondary: 25,
			intermediate: 55,
			universityEntrance: 18,
		},
		accessLevel: "hauptschule",
		subjects: ["Biologie", "Chemie", "Deutsch"],
		interests: ["Gesundheit", "Medizin", "Menschen helfen"],
		interestKeywords: ["arztpraxis", "medizin", "gesundheit", "patienten"],
		strengthTags: ["empathie", "sorgfalt", "kommunikation"],
		skillTags: ["Medizin", "Patientenbetreuung", "Organisation"],
		conditions: {
			...BASE_CONDITIONS,
			indoor: true,
			customerContact: true,
			teamwork: true,
			standingWalking: true,
			regulatedWork: true,
			precisionWork: true,
		},
		salaryMonthlyMedian: 2800,
		salaryKnown: true,
		digitalizationSignal: false,
		workLocations: "Arztpraxen, Kliniken, Ambulanzen",
		competenciesText: "Empathie, Sorgfalt, Kommunikationsstärke",
		germanOccupationCode: "81304",
	},
	{
		id: 10005,
		name: "Koch/Köchin",
		descriptionShort:
			"Berufstyp Anerkannter Ausbildungsberuf Ausbildungsart Duale Ausbildung in Gastronomie und Hotel Ausbildungsdauer 3 Jahre Lernorte Ausbildungsbetrieb und Berufsschule",
		descriptionLong: null,
		taskSummary: null,
		shortDescription:
			"Täglich frische Gerichte zubereiten und Menüs für Gäste kreieren.",
		taskBullets: [
			"Zutaten vorbereiten und Gerichte kochen",
			"Menüs planen und neue Rezepte ausprobieren",
			"Küche sauber halten und Hygieneregeln einhalten",
			"Im Team Bestellungen koordinieren",
		],
		images: [],
		degreeStats: {
			noQualification: 8,
			secondary: 40,
			intermediate: 38,
			universityEntrance: 14,
		},
		accessLevel: "hauptschule",
		subjects: ["Biologie", "Chemie", "Wirtschaft"],
		interests: ["Kochen", "Gastronomie", "Kreativität"],
		interestKeywords: ["küche", "kochen", "gastronomie", "restaurant"],
		strengthTags: ["kreativitaet", "teamarbeit", "belastbarkeit"],
		skillTags: ["Kochen", "Gastronomie", "Teamarbeit"],
		conditions: {
			...BASE_CONDITIONS,
			indoor: true,
			manualLabor: true,
			shiftWork: true,
			teamwork: true,
			standingWalking: true,
			irregularHours: true,
			changingTasks: true,
			noise: true,
		},
		salaryMonthlyMedian: 2400,
		salaryKnown: true,
		digitalizationSignal: false,
		workLocations: "Küchen in Restaurants, Hotels, Kantinen",
		competenciesText: "Kreativität, Teamfähigkeit, körperliche Belastbarkeit",
		germanOccupationCode: "29304",
	},
	{
		id: 10006,
		name: "Kaufmann/-frau im Einzelhandel",
		descriptionShort:
			"Berufstyp Anerkannter Ausbildungsberuf Ausbildungsart Duale Ausbildung in Handel Ausbildungsdauer 3 Jahre Lernorte Ausbildungsbetrieb und Berufsschule",
		descriptionLong: null,
		taskSummary: null,
		shortDescription:
			"Kunden beraten, Waren präsentieren und den Laden organisieren.",
		taskBullets: [
			"Kunden beraten und beim Kauf helfen",
			"Regale auffüllen und Preisschilder aktualisieren",
			"Ware annehmen und einlagern",
			"An der Kasse abrechnen",
		],
		images: [],
		degreeStats: {
			noQualification: 5,
			secondary: 35,
			intermediate: 45,
			universityEntrance: 15,
		},
		accessLevel: "hauptschule",
		subjects: ["Deutsch", "Mathematik", "Wirtschaft"],
		interests: ["Handel", "Kommunikation", "Verkauf"],
		interestKeywords: ["einzelhandel", "verkauf", "kunden", "handel"],
		strengthTags: ["kommunikation", "kundenorientierung", "freundlichkeit"],
		skillTags: ["Verkauf", "Kundenbetreuung", "Warenwirtschaft"],
		conditions: {
			...BASE_CONDITIONS,
			indoor: true,
			customerContact: true,
			teamwork: true,
			standingWalking: true,
			changingTasks: true,
		},
		salaryMonthlyMedian: 2300,
		salaryKnown: true,
		digitalizationSignal: false,
		workLocations: "Geschäfte, Kaufhäuser, Supermärkte",
		competenciesText:
			"Kundenorientierung, Kommunikationsstärke, Freundlichkeit",
		germanOccupationCode: "61204",
	},
	{
		id: 10007,
		name: "Tischler/in",
		descriptionShort:
			"Berufstyp Anerkannter Ausbildungsberuf Ausbildungsart Duale Ausbildung in Handwerk Ausbildungsdauer 3 Jahre Lernorte Ausbildungsbetrieb und Berufsschule",
		descriptionLong: null,
		taskSummary: null,
		shortDescription:
			"Möbel, Fenster und Treppen aus Holz entwerfen und herstellen.",
		taskBullets: [
			"Holz zuschneiden und bearbeiten",
			"Möbel und Holzteile zusammenbauen",
			"Oberflächen schleifen, lackieren und versiegeln",
			"Maße aufnehmen und nach Zeichnung arbeiten",
		],
		images: [],
		degreeStats: {
			noQualification: 6,
			secondary: 40,
			intermediate: 42,
			universityEntrance: 12,
		},
		accessLevel: "hauptschule",
		subjects: ["Mathematik", "Werken", "Physik"],
		interests: ["Handwerk", "Holz", "Gestaltung"],
		interestKeywords: ["tischler", "holz", "möbel", "handwerk"],
		strengthTags: ["handwerkliches-geschick", "praezision", "kreativitaet"],
		skillTags: ["Holzverarbeitung", "Handwerk", "Präzision"],
		conditions: {
			...BASE_CONDITIONS,
			indoor: true,
			workshop: true,
			manualLabor: true,
			machinery: true,
			noise: true,
			dirt: true,
			precisionWork: true,
			standingWalking: true,
		},
		salaryMonthlyMedian: 2700,
		salaryKnown: true,
		digitalizationSignal: false,
		workLocations: "Werkstätten, Baustellen, Kundenräume",
		competenciesText:
			"Handwerkliches Geschick, Sinn für Ästhetik, Präzision",
		germanOccupationCode: "34304",
	},
	{
		id: 10008,
		name: "Erzieher/in",
		descriptionShort:
			"Berufstyp Anerkannter Ausbildungsberuf Ausbildungsart Schulische Ausbildung Ausbildungsdauer 3 Jahre Lernorte Fachschule und Praxiseinrichtung",
		descriptionLong: null,
		taskSummary: null,
		shortDescription:
			"Kinder in ihrer Entwicklung begleiten und pädagogische Angebote gestalten.",
		taskBullets: [
			"Kinder beim Spielen und Lernen begleiten",
			"Basteln, Singen und Bewegungsangebote leiten",
			"Elterngespräche führen und dokumentieren",
			"Entwicklung der Kinder beobachten und fördern",
		],
		images: [],
		degreeStats: {
			noQualification: 1,
			secondary: 10,
			intermediate: 45,
			universityEntrance: 44,
		},
		accessLevel: "realschule",
		subjects: ["Deutsch", "Biologie", "Sozialkunde"],
		interests: ["Kinder", "Pädagogik", "Soziales"],
		interestKeywords: ["kinder", "erziehung", "pädagogik", "sozial"],
		strengthTags: ["empathie", "kreativitaet", "kommunikation"],
		skillTags: ["Pädagogik", "Kinderbetreuung", "Kommunikation"],
		conditions: {
			...BASE_CONDITIONS,
			indoor: true,
			outdoor: true,
			customerContact: true,
			teamwork: true,
			standingWalking: true,
			changingTasks: true,
			regulatedWork: true,
		},
		salaryMonthlyMedian: null,
		salaryKnown: false,
		digitalizationSignal: false,
		workLocations: "Kitas, Schulen, Jugendzentren",
		competenciesText: "Empathie, Kreativität, Kommunikationsstärke",
		germanOccupationCode: "83104",
	},
];

export const MOCK_OCCUPATIONS = new Map<number, Occupation>(
	MOCK_OCCUPATIONS_LIST.map((o) => [o.id, o]),
);
