export type {
	OccupationPredicate,
	WorkExpectationPredicate,
	WorkPreferenceOptionChecks,
} from "@azuki/shared";
export {
	COMMUNICATION_SKILL_TAGS,
	CONCENTRATION_SKILL_TAGS,
	CRAFTSMANSHIP_SKILL_TAGS,
	CREATIVITY_SKILL_TAGS,
	CREATIVITY_STRENGTH_TAG,
	hasCreativitySignal,
	LOGICAL_THINKING_SKILL_TAGS,
	NO_GO_MAP,
	PRECISION_SKILL_TAGS,
	STRENGTH_TO_TAGS,
	WORK_EXPECTATIONS_CHECKS,
	WORK_PREF_MAP,
} from "@azuki/shared";

export {
	PRACTICAL_EXPERIENCE_CATEGORY_WEIGHT,
	PRACTICAL_EXPERIENCE_DEFAULT_CATEGORY_WEIGHT,
	PRACTICAL_EXPERIENCE_KEYWORD_HIT_CAP,
	PRACTICAL_EXPERIENCE_POINT_PER_HIT,
	PRACTICAL_EXPERIENCE_RATING_MULTIPLIER,
	PRACTICAL_EXPERIENCE_SCORE_CAP,
} from "@azuki/shared";
